root = "."
tmp_dir = "tmp"

[build]
  cmd = "cd backend && go build -o ../tmp/main ."
  bin = "./tmp/main"
  delay = 1000
  exclude_dir = ["frontend", "tmp", "node_modules"]
  exclude_regex = ["_test.go"]
  include_ext = ["go"]
  kill_delay = "2s"

[log]
  time = false

[misc]
  clean_on_exit = true
